export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const GET_EVENT = 'GET_EVENT';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const CHECK_EVENT_CODE_SUCCESS = 'CHECK_EVENT_SUCCESS';
export const GET_EVENT_ROOM_SUCCESS = 'GET_EVENT_ROOM_SUCCESS';
export const CHECK_EVENT_CODE = 'CHECK_EVENT_CODE';
export const EVENT_CODE_CHECKED = 'EVENT_CODE_CHECKED';
export const CHECK_EVENT_CODE_FAILURE = 'CHECK_EVENT_CODE_FAILURE';
export const TYPE_QUESTION = 'TYPE_QUESTION';
export const TYPE_AUTHOR = 'TYPE_AUTHOR';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const SUBMIT_QUESTION_SUCCESS = 'SUBMIT_QUESTION_SUCCESS';
export const RECEIVE_NEW_QUESTION = 'RECEIVE_NEW_QUESTION';

export const VOTE_QUESTION = 'VOTE_QUESTION';
export const VOTE_QUESTION_SUCCESS = 'VOTE_QUESTION_SUCCESS';
export const RECEIVE_QUESTION_UPDATED = 'RECEIVE_QUESTION_UPDATED';
export const RECEIVE_QUESTION_DELETED = 'RECEIVE_QUESTION_DELETED';

export const QUESTION_SORT_CHANGED = 'QUESTION_SORT_CHANGED';